services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: gsbomounworjrjartfdy.db.eu-central-1.nhost.run
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: gsbomounworjrjartfdy
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        value: tyJNgQh5PQ1DBjg4
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: "5678"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: DB_POSTGRESDB_CONNECTION_TIMEOUT
        value: "20000"
      - key: N8N_DEFAULT_BINARY_DATA_MODE
        value: filesystem
      - key: EXECUTIONS_DATA_PRUNE
        value: "true"
      - key: N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN
        value: "true"
        - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: PGSSLMODE
        value: no-verify
